# Generated by Django 3.2.4 on 2022-10-16 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometable',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hometable',
            name='updated_at',
        ),
    ]
