# Generated by Django 3.2.4 on 2022-11-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20221105_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometable',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
